version: '3.4'

services:
  ms.rabbitmq.bus:
    container_name: ms.rabbitmq.bus
    restart: always
    ports:
     - "5672:5672"
     - "15672:15672"

  ms.mongo.attendances.db:
    container_name: ms.mongo.attendances.db
    restart: always
    volumes:
      -  ./data/mongo:/data/db
    ports:
      - "27019:27017"

  ms.cassandra.db:
    container_name: ms.cassandra.db
    restart: always
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"
       
  ms.sql.employees.db:
    container_name: ms.sql.employees.db
    restart: always
    volumes:
      - ./data/sqlServer:/var/opt/mssql/data
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: ".123Pass456."
      ACCEPT_EULA: "Y"

  ms.employees.api:
    container_name: ms.employees.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:EmployeeDB=Data Source=ms.sql.employees.db; Initial Catalog=EmployeesAttendance; User ID=sa; Password=.123Pass456.; MultipleActiveResultSets=True;"
      - "Communication:EventBus:HostName=ms.rabbitmq.bus"
      - "Communication:External:AttendanceApiUrl=http://ms.attendances.api:80"
    ports:
      - "9010:80"
    depends_on:
      - ms.sql.employees.db
      - ms.rabbitmq.bus
      - ms.attendances.api

  ms.users.api:
    container_name: ms.users.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:Hostname=ms.cassandra.db"
      - "Communication:EventBus:HostName=ms.rabbitmq.bus" 
    ports:
      - "9009:80"
    depends_on:
      - ms.cassandra.db
      - ms.rabbitmq.bus

  ms.attendances.api:
    container_name: ms.attendances.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MongoDB=mongodb://ms.mongo.attendances.db:27017"
      - "ConnectionStrings:AttendanceDB=DbHistoricalAttendance"
      - "ConnectionStrings:AttendanceCollection=Attendances"
      - "Communication:EventBus:HostName=ms.rabbitmq.bus"
    ports:
      - "9020:80"
    depends_on:
      - ms.mongo.attendances.db 
      - ms.rabbitmq.bus
